### ISSUE TITLE
префикс $ 

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/game-of-life#11]
`this.$startButton = $("#startButton")[0] as HTMLButtonElement;`

У TS же есть JQuery object. Префикс $ показывает, что элемент является JQuery объектом. У тебя же это HTMLElement.

Префикс полезен, когда с твоим кодом будет работать другой человек. Ему не нужно будет разбираться какие методы можно применять к переменной (каким объектом она является) - по префиксу сразу будет ясно.

**Comment by kinda-neat** [comment]
Принято) плиз посмотри все ли сейчас как надо
