### ISSUE TITLE
циклы for

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/game-of-life#14]
По максимуму заменить циклы for на перебирающие методы массивов

**Comment by kinda-neat** [comment]
Но здесь только одно место где я работаю с массивом, это https://github.com/Maksimus-Prime/game-of-life/blob/1b656c205a8434fd80d6a8beaa9a84ade0f50b4f/src/mvc/model.ts#L91
Или здесь идет речь о использовании Object.keys()? пример: https://stackoverflow.com/a/14810722/8124296

**Comment by kinda-neat** [comment]
Исправил. Могу закрывать ишьюс?
