### ISSUE TITLE
сделать в js отступы в два пробела

### ISSUE THREAD

**Issue by shevdi** [Maksimus-Prime/game-of-life#18]

**Comment by kinda-neat** [comment]
В стандартах есть такой пункт? Не нашел, поэтому делал как в стандартах по CSS (4 пробела)

**Comment by shevdi** [comment]
Правило такое есть, но в стандартах похоже не прописано. У нас во всех проектах eslint настроен на два пробела.

**Comment by kinda-neat** [comment]
Принято) В стандартах можно прописать правило для отступов js (исключите как раз такой issue для всех будущих стажеров), раз в css на это обратили внимание)
