### ISSUE TITLE
Все интерфейсы в отдельный файл / реализовать интерфейсы

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/game-of-life#28]
Все интерфейсы следует описывать в отдельных файлах .  можно в один файл все разместить. И самое главное: интерфейсы должны быть реализованы классом . То есть, например,  класс контроллера должен реализовывать его интерфейс: `class Controller implements IController`.

**Comment by kinda-neat** [comment]
Burize, я вынес все интерфейсы в отдельный файл и где нужно их импортил, дореализовал некоторые интерфейсы и в отношении классов так и сделал class `Controller implements IController`. Плиз посмотри коммит, все ли я сделал
