### ISSUE TITLE
Названия булевых переменных

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/game-of-life#29]
В целом названы как нужно. Но в некоторых местах нужно подправить.
Для булевых переменных https://github.com/airbnb/javascript#accessors--boolean-prefix
```
interface ICell {
  x: number;
  y: number;
  alive: boolean;
}
```
ну и весь проект проверить на это. (где-то правильно названо, где-то - наверно забыл подправить)

**Comment by kinda-neat** [comment]
Я не понял что ты от меня хочешь, ты хочешь чтобы я добавил в интерфейс метод isAlive() и заменил везде где от значения alive что-то зависит? Сейчас я вынес Cell в отдельный класс, который буду использовать в model

**Comment by Burize** [comment]
`public stopGame: boolean;` Имелось ввиду префиксы для названия булевых переменных. То есть должно начинаться с `is` или `has`.  Но вынести Cell в отдельный класс так же является правильным решением)
Можно закрыть issue - только stopGame подправь .

**Comment by kinda-neat** [comment]
Насчет Cell принято, насчет префиксов все изи, только разве это нормально что я Свойство назову `isStopGame`? В ссылке что ты дал, там в примерах приведены функции, да и префиксы is, has как бы намекают на действия. Кстати, заглянул сейчас в класс Model, там есть такое свойство как `public stopGame: boolean;`, так при этом есть еще и функция
```
public isGameStop(): boolean {
  return this.stopGame;
}
```

**Comment by Burize** [comment]
` разве это нормально что я Свойство назову isStopGame? `  Ну вообще да .  
` префиксы is, has как бы намекают на действия ` Насчет has не знаю, но `is` все же означает состояние. И как раз таки этот префикс позволяет понять, что это не функция, а переменная(или  getter ) булевского типа. 

`Это issue у всех есть. Я был уверен, что оно есть в стандартах, но оказывается нет.

` Кстати, заглянул сейчас в класс Model, там есть такое свойство как public stopGame: boolean;, так при этом есть еще и функция `. Да сейчас не логично выглядит по названием. 
Эта функция используется как getter. Их обычно используют:
+ когда возвращают значение приватной переменной. То есть напрямую к переменной нельзя обратиться но можно получить ее через геттер. Приватные переменные называют с "_" .  В этом случае булевое поле называлось бы _isStopGame а функция (геттер) isStopGame;
+ Когда значение свойства вычисляемо. То есть нельзя было бы без расчетов определить на паузе игра сейчас или нет. Соответсвенно тогда бы и не было булева поля - была бы только функция(геттер). И по именам тоже было бы все логично.

Сейчас получается немного бессмысленно, в том плане, что есть публичное поле и есть публичный метод, который делает только то, что возвращает значение этого поля, к которому и так можно обратиться напрямую. Поэтому и наложение в именах. 

По той ссылке, которую я кидал, если использовать функцию в качестве геттера, то лучше их называть с преффиксом `get. То есть что то типо getGameStatus (ну или что-то по лучше придумать... но getPauseGame наверное не очень правильно будет)
