### ISSUE TITLE
getModel & getView излишни

### ISSUE THREAD

**Issue by Znack** [Maksimus-Prime/game-of-life#49]
Они по сути только заставляют тебя дублировать код и главное, вносят неочевидную зависимость — каждый раз при добавлении метода надо туда его еще пробрасывать, об этом легко забыть даже тебе через пару неделек будет, а что говорить, если проект будут другие люди поддерживать. Просто несколько часов может запросто потеряно на поиск такой вот баги, что просто забыл в getModel новый метод прокинуть. И в целом всегда с подозрением относись к такому коду, где нужно повторно дублировать список чего бы то ни было, чтобы все начало работать. Все в идеале должно автоматически подхватывать в таких случаях, а у тебя тут можно просто инстанс и передавать на самом деле

>  «Пишите код так, как будто сопровождать его будет склонный к насилию психопат, который знает, где вы живёте»
:)

**Comment by kinda-neat** [comment]
Принято, все учту) Самому было противно вот так внутренности каждого метода оборачивать
